// <auto-generated />
namespace Car_Rental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alter_tableClient_addField_isAdmin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_tableClient_addField_isAdmin));
        
        string IMigrationMetadata.Id
        {
            get { return "202201141200463_alter_tableClient_addField_isAdmin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
